name: lista_detalhes
description: Um novo projeto Flutter

publish_to: 'none' 

environment:
  sdk: "^3.7.0" 

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
